prog1:enigmestat.o mainenig.o
	gcc enigmestat.o mainenig.o -o prog1 -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
mainenig.o:mainenig.c	
	gcc -c mainenig.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
enigmestat.o:enigmestat.c
	gcc -c enigmestat.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
