prog:ennemi.o main.o
	gcc ennemi.o main.o -o prog -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
main.o:main.c	
	gcc -c main.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
fichier.o:ennemi.c
	gcc -c ennemi.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
