prog:enigmealeatoire.o main.o
	gcc enigmealeatoire.o main.o -o prog -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
main.o:main.c	
	gcc -c main.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
enigmealeatoire.o:enigmealeatoire.c
	gcc -c enigmealeatoire.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
