travail:background.o main.o fonction.o hero.o jeux.o
	gcc background.o main.o fonction.o hero.o jeux.o -o travail -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
main.o:main.c	
	gcc -c main.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
background.o:background.c
	gcc -c background.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
fonction.o:fonction.c
	gcc -c fonction.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
hero.o:hero.c
	gcc -c hero.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g	
jeux.o:jeux.c
	gcc -c jeux.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf -g
